### ISSUE TITLE
Cannot see reviews over tramp

### ISSUE THREAD

**Issue by guillaumekoenig** [terranpro/magit-gerrit#29]
Hello,

I am having an issue when using magit-gerrit over tramp. `(executable-find "ssh")` on my local system returns "/run/current-system/sw/bin/ssh", which is the path for ssh on NixOS. This is the value set to magit-git-executable before performing the call. It works well locally. But when I am running magit-gerrit over tramp, it will also use that path to locate ssh. The problem is it's invalid if ssh is installed elsewhere (typically /usr/bin).

So the problem is picking up the local path to use on the server connected over tramp. Replacing the calls to (executable-find "ssh") with simply "ssh" fixes it for me. Magit also seems to issue its commands with simply "git" (ie, not the full path).

Cheers

**Comment by terranpro** [comment]
Hi!

Thanks for the report.  This sounds like a simple and reasonable fix, but I haven't pushed it yet because I haven't been able to get magit working with TRAMP yet to reproduce this.  

The `find-executable` usage can probably be removed anyways - I think it was used in older versions of magit or magit plugins and I borrowed the usage from there - but I would like to verify it working locally if possible.

I grabbed the latest magit (master branch), but when I try to run `magit-status` on a TRAMP buffer that has a git repo, it asks if I would like to create a git repository at that location.

Could you share your magit and Emacs versions?

Thanks again

**Comment by guillaumekoenig** [comment]
Hi terranpro,

`M-x magit-version` reports `Magit 20151025.1115, Git 2.1.4, Emacs 24.5.2`. Hope that helps. I believe magit-status reads `default-directory` to look for the git repository, which evaluates to a tramp path for me. Maybe somehow this is not set properly when you are testing ?

Thanks for magit-gerrit it's really great to be able to review commits without leaving emacs. The one missing killer feature is the ability to comment on a line basis. Maybe for displaying comments inline something a la magit-blame would do, but entering comments from the UI sounds more challenging.

Cheers

**Comment by guillaumekoenig** [comment]
Hello, have you been able to check magit-gerrit over tramp ?

**Comment by terranpro** [comment]
Hi!

I went ahead and submitted your suggested fix already in the `next` branch with commit 93dd874e0c22bb8ac514f22cb76e1b5bf802e9ed.  After several failed attempts I finally discovered it was because my system `git` version was too old to my custom version that was in a special path under my home directory.  After checking the tramp info page a bit I found =)

`(add-to-list 'tramp-remote-path 'tramp-own-remote-path)`

I just verified your fix, and I can see reviews now through magit+tramp.  I'll share this fix with the `master` branch as well.


Thanks for the kind words; I also miss the ability to comment on code directly, but it's mostly because things would get more tricky using the REST API, and like you said some kind of customizing of magit-blame / diff modes.  In the beginning, I was also trying to keep it simple and minimize external dependencies as well (request.el), but it might be fun to push the limits now that things work somewhat!

**Comment by guillaumekoenig** [comment]
Ah good job on finding tramp-own-remote-path, that's a very useful setting when working with tramp.

I believe there's a typo in the next commit : magit-gerrit-build-popup should really be magit-gerrit-popup, no ? Using the tip, magit-gerrit cannot open its popup anymore.

Anyway thanks again, I'll check from time to time for any update on the plugin :)

**Comment by terranpro** [comment]
D'oh yes I did just break `master` with a bad cherry pick from `next`

Fixed - thanks again!
